openapi: '3.0.2'
info:
  title: openthingy ERP API
  version: '1.0'
servers:
  - url: https://demo.erp.openthingy.com/
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
